# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3.39"
tasks:
  default:
    cmds:
      - cmd: task --list
        silent: true
  bootstrap:
    desc: "Bootstrap Go toolchain"
    cmds:
      - ./bootstrap.sh --clean --build --github-actions
  clean:
    desc: "Clean build artifacts"
    cmds:
      - ./bootstrap.sh --clean
